# Generated by Django 5.1.3 on 2024-11-27 06:21

import datetime
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('website_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_button_text', models.CharField(default='click', max_length=50)),
                ('banner_text', models.TextField(blank=True, null=True)),
                ('welcome_message', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_1', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_2', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_3', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'template': 'blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'form_classname': 'full richtext', 'template': 'blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'form_classname': 'full image', 'template': 'blocks/image_block.html'})}, null=True)),
                ('marquee_text', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_images', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Display Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code_snippet', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='DisplayPageSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_page_sponsors', to='display.displaypage')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_page_sponsors', to='display.sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='displaypage',
            name='sponsors',
            field=models.ManyToManyField(related_name='display_pages', through='display.DisplayPageSponsor', to='display.sponsor'),
        ),
    ]
