# Generated by Django 5.1.3 on 2024-11-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userinfo_IndexPage',
            new_name='userinfoIndexPage',
        ),
    ]
